### ISSUE TITLE
Capability to validate bootstrap usernames

### ISSUE THREAD

**Issue by binod33** [dasein-cloud/dasein-cloud-core#20] opened 2015-09-01 17:15 UTC
Some clouds like azure does support providing bootstrap usernames during launch, but there are limitations on what words can be used,
like for azure, "root" on linux and "administrator" on a windows are not allowed.

but for azurepack it seems that those usernames are valid.

GCE has the "administrator" reserved so it cannot be used. 

The variation in supported usernames can be based on platforms for each cloud.

**Comment by drewlyall** [comment] 2015-09-29 16:37
This is a dupe of #17

**Closed as completed by drewlyall** 2015-09-29 16:37 UTC
